routingRules:
  - domain: "energy-trade"  # P2P Trading domain
    version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-utilitybpp:3003/api/webhook"
    endpoints:
      - init  # cascaded init from P2P Trading BPP
      - confirm  # cascaded confirm from P2P Trading BPP

schemaValidator:
  id: schemav2validator
  config:
    type: url
    location: https://raw.githubusercontent.com/beckn/protocol-specifications-new/refs/heads/main/api/beckn.yaml
    cacheTTL: "3600"

