routingRules:
  - domain: "beckn.one:deg:ev-charging:2.0.0"  # Retail domain
    version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_status
      - on_cancel
      - on_update
      - on_select
      - on_init
      - on_confirm
      - on_track
      - on_rating
      - on_support

  - domain: "energy-trade"  # P2P Trading domain
    version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - init # cascaded init to utility bpp
      - confirm # cascaded confirm to utility bpp

schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-new/refs/heads/main/api/beckn.yaml
            cacheTTL: "3600"