routingRules:
  - version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_status
      - on_cancel
      - on_update
      - on_select
      - on_init
      - on_confirm
      - on_track
      - on_rating
      - on_support

  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - init # cascaded init to utility bpp
      - confirm # cascaded confirm to utility bpp
