routingRules:
  - domain: "beckn.one:deg:ev-charging:2.0.0"  # Retail domain
    version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-bpp:3002/api/webhook"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

  - domain: "energy-trade"  # P2P Trading domain
    version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-bpp:3002/api/webhook"
    endpoints:
      - on_init #response from utility bpp to cascaded init request
      - on_confirm #response from utility bpp to cascaded confirm request
      - on_update #update from utility bpp after fulfillment